global:
  scrape_interval:     15s 

alerting:
  alertmanagers:
  - static_configs:
    - targets:

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090','localhost:9100','localhost:9115']
  
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
     module: [http_2xx]  # Probes for 2xx responses only
    static_configs:
     - targets:
       - http://13.235.254.169:80/
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - target_label: instance
       replacement: localhost
     - target_label: __address__
       replacement: localhost:9115  # Blackbox Exporter
