name: Deploy Latest Docker Image to Prod

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Get latest tag from dev repo
      run: |
        latest_tag=$(curl -s "https://hub.docker.com/v2/repositories/pravinrajmarimuthu/my-react-app-dev/tags/?page_size=1" | jq -r '.results[0].name')
        echo "Latest tag from dev: $latest_tag"
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV

    - name: Pull Docker image with latest tag from dev
      run: |
        docker pull pravinrajmarimuthu/my-react-app-dev:${{ env.latest_tag }}

    - name: Retag image for prod repo
      run: |
        docker tag pravinrajmarimuthu/my-react-app-dev:${{ env.latest_tag }} pravinrajmarimuthu/my-react-app-prod:${{ env.latest_tag }}

    - name: Push image to prod repo
      run: |
        docker push pravinrajmarimuthu/my-react-app-prod:${{ env.latest_tag }}
